# Generated by Django 5.1.2 on 2024-10-10 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registered_users',
            name='Test',
            field=models.CharField(default='DefaultTestValue', max_length=100),
        ),
    ]
