# Generated by Django 5.1.2 on 2024-10-14 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_registered_users_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registered_users',
            name='Test',
        ),
    ]
